stages:
    - prepare

compile:
  stage: prepare
  tags:
    - docker
  image: cern/cc7-base
  script:
    - yum install git less -y
    - eval `ssh-agent -s`
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa
    - chmod 700 /root/.ssh/id_rsa
    - git remote add upstream git@github.com:petricm/DIRACtest.git
    - git remote -vv
    - ssh-keyscan -H github.com >> /root/.ssh/known_hosts
    - git fetch upstream